include:
  - project: 'zkovari/gitlab-ci-templates'
    file: 'java/gradle/base.yml'
  - project: 'zkovari/gitlab-ci-templates'
    file: 'code-quality.yml'

.latest gradle job template:
  image: gradle:latest
  allow_failure: true

.integTest job template:
  extends: .test template
  stage: integTest
  needs: [Build]
  script:
    - ./gradlew test --tests *FunctionalTest*

Build:
  extends: .single project build template

Build with latest Gradle:
  extends:
    - .build template
    - .latest gradle job template
  script: gradle assemble -s

Test:
  extends: .single project test template

Test with latest Gradle:
  extends:
   - .test template
   - .latest gradle job template
  needs: [Build with latest Gradle]
  script:
    - gradle check
  artifacts:
    reports:
      junit: build/test-results/**/TEST-*.xml

IntegTest Gradle 3:
  extends: .integTest job template
  variables:
    GRADLE_VERSION_FOR_SYSTEM_TESTS: "3.0"

IntegTest Gradle 4:
  extends: .integTest job template
  variables:
    GRADLE_VERSION_FOR_SYSTEM_TESTS: "4.0"

IntegTest Gradle 5:
  extends: .integTest job template
  variables:
    GRADLE_VERSION_FOR_SYSTEM_TESTS: "5.0"

IntegTest Gradle 6:
  extends: .integTest job template
  variables:
    GRADLE_VERSION_FOR_SYSTEM_TESTS: "6.0"

Deploy to plugin portal:
  extends: .deploy to plugin portal template

Deploy to Bintray:
  extends: .deploy to Bintray template
